---
language: python
services: docker
env:
  global:
    - ROLE_NAME: ansible-role-vault
  matrix:
    - MOLECULE_DISTRO: amazonlinux2
install:
  - pip install molecule==2.22 docker
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
