---
- name: Install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ vault_os_packages }}"

- name: Remote Vault Dir
  file:
    path: /tmp/vault
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

- name: Download Vault
  get_url:
    url: "{{ vault_url }}"
    dest: "/tmp/vault/{{ vault_zip }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

- name: Unarchive Vault
  unarchive:
    remote_src: true
    src: "/tmp/vault/{{ vault_zip }}"
    dest: "{{ vault_bin }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755

- name: Clean up
  file:
    path: /tmp/vault
    state: absent
    changed_when: false
