---
- name: Include OS vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Vault Group
  become: true
  group:
    name: "{{ vault_group }}"
    state: present

- name: Vault User
  become: true
  user:
    name: "{{ vault_user }}"
    comment: "Vault user"
    group: "{{ vault_group }}"
    system: true

- name: Create directories
  become: true
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
  with_items:
    - "{{ vault_log }}"
    - "{{ vault_dir }}"
    - "{{ vault_dir }}/ssl"

- name: Copy Vault configure file
  become: true
  copy:
    src: vault.hcl
    dest: "{{ vault_main_config }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0400

- name: Vault systemd file
  become: true
  template:
    src: vault.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: "{{ vault_group }}"
    mode: 0644

- name: Include install
  include: install.yml

- name: Check mlock capability
  become: true
  command: "setcap cap_ipc_lock=+ep {{ vault_main_config }}"
  changed_when: false
  ignore_errors: true
  register: vault_mlock_capability

- name: Enable non root mlock
  become: true
  command: "setcap cap_ipc_lock=+ep {{ vault_main_config }}"
  when: vault_mlock_capability is failed
